/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSageRouteImport } from './routes/api/sage'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSageRouteImport } from './routes/_authenticated/sage'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedQuickmeetRouteImport } from './routes/_authenticated/quickmeet'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFocusRouteImport } from './routes/_authenticated/focus'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedCommunitiesRouteImport } from './routes/_authenticated/communities'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'
import { Route as AuthenticatedNetworkUserIdRouteImport } from './routes/_authenticated/network.$userId'
import { Route as AuthenticatedCommunitiesNewRouteImport } from './routes/_authenticated/communities_.new'
import { Route as AuthenticatedCommunitiesIdRouteImport } from './routes/_authenticated/communities_.$id'
import { Route as AuthenticatedMessagesDmIdRouteImport } from './routes/_authenticated/messages.dm.$id'
import { Route as AuthenticatedCommunitiesIdChannelRouteImport } from './routes/_authenticated/communities_.$id.$channel'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSageRoute = ApiSageRouteImport.update({
  id: '/api/sage',
  path: '/api/sage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSageRoute = AuthenticatedSageRouteImport.update({
  id: '/sage',
  path: '/sage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuickmeetRoute = AuthenticatedQuickmeetRouteImport.update({
  id: '/quickmeet',
  path: '/quickmeet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFocusRoute = AuthenticatedFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunitiesRoute =
  AuthenticatedCommunitiesRouteImport.update({
    id: '/communities',
    path: '/communities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNetworkUserIdRoute =
  AuthenticatedNetworkUserIdRouteImport.update({
    id: '/network/$userId',
    path: '/network/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommunitiesNewRoute =
  AuthenticatedCommunitiesNewRouteImport.update({
    id: '/communities_/new',
    path: '/communities/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommunitiesIdRoute =
  AuthenticatedCommunitiesIdRouteImport.update({
    id: '/communities_/$id',
    path: '/communities/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesDmIdRoute =
  AuthenticatedMessagesDmIdRouteImport.update({
    id: '/dm/$id',
    path: '/dm/$id',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedCommunitiesIdChannelRoute =
  AuthenticatedCommunitiesIdChannelRouteImport.update({
    id: '/$channel',
    path: '/$channel',
    getParentRoute: () => AuthenticatedCommunitiesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/home': typeof AuthenticatedHomeRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quickmeet': typeof AuthenticatedQuickmeetRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/sage': typeof AuthenticatedSageRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/sage': typeof ApiSageRoute
  '/communities/$id': typeof AuthenticatedCommunitiesIdRouteWithChildren
  '/communities/new': typeof AuthenticatedCommunitiesNewRoute
  '/network/$userId': typeof AuthenticatedNetworkUserIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/communities/$id/$channel': typeof AuthenticatedCommunitiesIdChannelRoute
  '/messages/dm/$id': typeof AuthenticatedMessagesDmIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/home': typeof AuthenticatedHomeRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quickmeet': typeof AuthenticatedQuickmeetRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/sage': typeof AuthenticatedSageRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/sage': typeof ApiSageRoute
  '/communities/$id': typeof AuthenticatedCommunitiesIdRouteWithChildren
  '/communities/new': typeof AuthenticatedCommunitiesNewRoute
  '/network/$userId': typeof AuthenticatedNetworkUserIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/communities/$id/$channel': typeof AuthenticatedCommunitiesIdChannelRoute
  '/messages/dm/$id': typeof AuthenticatedMessagesDmIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/communities': typeof AuthenticatedCommunitiesRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/focus': typeof AuthenticatedFocusRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quickmeet': typeof AuthenticatedQuickmeetRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/sage': typeof AuthenticatedSageRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/api/sage': typeof ApiSageRoute
  '/_authenticated/communities_/$id': typeof AuthenticatedCommunitiesIdRouteWithChildren
  '/_authenticated/communities_/new': typeof AuthenticatedCommunitiesNewRoute
  '/_authenticated/network/$userId': typeof AuthenticatedNetworkUserIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/_authenticated/communities_/$id/$channel': typeof AuthenticatedCommunitiesIdChannelRoute
  '/_authenticated/messages/dm/$id': typeof AuthenticatedMessagesDmIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/communities'
    | '/discover'
    | '/focus'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/quickmeet'
    | '/rooms'
    | '/sage'
    | '/settings'
    | '/tasks'
    | '/api/sage'
    | '/communities/$id'
    | '/communities/new'
    | '/network/$userId'
    | '/auth/google/callback'
    | '/communities/$id/$channel'
    | '/messages/dm/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/communities'
    | '/discover'
    | '/focus'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/quickmeet'
    | '/rooms'
    | '/sage'
    | '/settings'
    | '/tasks'
    | '/api/sage'
    | '/communities/$id'
    | '/communities/new'
    | '/network/$userId'
    | '/auth/google/callback'
    | '/communities/$id/$channel'
    | '/messages/dm/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/analytics'
    | '/_authenticated/communities'
    | '/_authenticated/discover'
    | '/_authenticated/focus'
    | '/_authenticated/home'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/quickmeet'
    | '/_authenticated/rooms'
    | '/_authenticated/sage'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/api/sage'
    | '/_authenticated/communities_/$id'
    | '/_authenticated/communities_/new'
    | '/_authenticated/network/$userId'
    | '/auth/google/callback'
    | '/_authenticated/communities_/$id/$channel'
    | '/_authenticated/messages/dm/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiSageRoute: typeof ApiSageRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sage': {
      id: '/api/sage'
      path: '/api/sage'
      fullPath: '/api/sage'
      preLoaderRoute: typeof ApiSageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sage': {
      id: '/_authenticated/sage'
      path: '/sage'
      fullPath: '/sage'
      preLoaderRoute: typeof AuthenticatedSageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quickmeet': {
      id: '/_authenticated/quickmeet'
      path: '/quickmeet'
      fullPath: '/quickmeet'
      preLoaderRoute: typeof AuthenticatedQuickmeetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/focus': {
      id: '/_authenticated/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof AuthenticatedFocusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/communities': {
      id: '/_authenticated/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof AuthenticatedCommunitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/network/$userId': {
      id: '/_authenticated/network/$userId'
      path: '/network/$userId'
      fullPath: '/network/$userId'
      preLoaderRoute: typeof AuthenticatedNetworkUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/communities_/new': {
      id: '/_authenticated/communities_/new'
      path: '/communities/new'
      fullPath: '/communities/new'
      preLoaderRoute: typeof AuthenticatedCommunitiesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/communities_/$id': {
      id: '/_authenticated/communities_/$id'
      path: '/communities/$id'
      fullPath: '/communities/$id'
      preLoaderRoute: typeof AuthenticatedCommunitiesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages/dm/$id': {
      id: '/_authenticated/messages/dm/$id'
      path: '/dm/$id'
      fullPath: '/messages/dm/$id'
      preLoaderRoute: typeof AuthenticatedMessagesDmIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/communities_/$id/$channel': {
      id: '/_authenticated/communities_/$id/$channel'
      path: '/$channel'
      fullPath: '/communities/$id/$channel'
      preLoaderRoute: typeof AuthenticatedCommunitiesIdChannelRouteImport
      parentRoute: typeof AuthenticatedCommunitiesIdRoute
    }
  }
}

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesDmIdRoute: typeof AuthenticatedMessagesDmIdRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesDmIdRoute: AuthenticatedMessagesDmIdRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedCommunitiesIdRouteChildren {
  AuthenticatedCommunitiesIdChannelRoute: typeof AuthenticatedCommunitiesIdChannelRoute
}

const AuthenticatedCommunitiesIdRouteChildren: AuthenticatedCommunitiesIdRouteChildren =
  {
    AuthenticatedCommunitiesIdChannelRoute:
      AuthenticatedCommunitiesIdChannelRoute,
  }

const AuthenticatedCommunitiesIdRouteWithChildren =
  AuthenticatedCommunitiesIdRoute._addFileChildren(
    AuthenticatedCommunitiesIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCommunitiesRoute: typeof AuthenticatedCommunitiesRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedFocusRoute: typeof AuthenticatedFocusRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuickmeetRoute: typeof AuthenticatedQuickmeetRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedSageRoute: typeof AuthenticatedSageRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedCommunitiesIdRoute: typeof AuthenticatedCommunitiesIdRouteWithChildren
  AuthenticatedCommunitiesNewRoute: typeof AuthenticatedCommunitiesNewRoute
  AuthenticatedNetworkUserIdRoute: typeof AuthenticatedNetworkUserIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCommunitiesRoute: AuthenticatedCommunitiesRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedFocusRoute: AuthenticatedFocusRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuickmeetRoute: AuthenticatedQuickmeetRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedSageRoute: AuthenticatedSageRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedCommunitiesIdRoute: AuthenticatedCommunitiesIdRouteWithChildren,
  AuthenticatedCommunitiesNewRoute: AuthenticatedCommunitiesNewRoute,
  AuthenticatedNetworkUserIdRoute: AuthenticatedNetworkUserIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiSageRoute: ApiSageRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
