/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFocusRouteImport } from './routes/_authenticated/focus'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedSageRouteImport } from './routes/_authenticated/sage'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const mkChild = (imp: any, id: string) => imp.update({ id, path: id, getParentRoute: () => AuthenticatedRoute } as any)

const AuthenticatedHomeRoute = mkChild(AuthenticatedHomeRouteImport, '/home')
const AuthenticatedFocusRoute = mkChild(AuthenticatedFocusRouteImport, '/focus')
const AuthenticatedTasksRoute = mkChild(AuthenticatedTasksRouteImport, '/tasks')
const AuthenticatedRoomsRoute = mkChild(AuthenticatedRoomsRouteImport, '/rooms')
const AuthenticatedSageRoute = mkChild(AuthenticatedSageRouteImport, '/sage')
const AuthenticatedProfileRoute = mkChild(AuthenticatedProfileRouteImport, '/profile')
const AuthenticatedNotificationsRoute = mkChild(AuthenticatedNotificationsRouteImport, '/notifications')
const AuthenticatedAnalyticsRoute = mkChild(AuthenticatedAnalyticsRouteImport, '/analytics')
const AuthenticatedSettingsRoute = mkChild(AuthenticatedSettingsRouteImport, '/settings')

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthenticatedHomeRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/sage': typeof AuthenticatedSageRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/focus': typeof AuthenticatedFocusRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/sage': typeof AuthenticatedSageRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/focus'
    | '/tasks'
    | '/rooms'
    | '/sage'
    | '/profile'
    | '/notifications'
    | '/analytics'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/focus'
    | '/tasks'
    | '/rooms'
    | '/sage'
    | '/profile'
    | '/notifications'
    | '/analytics'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/home'
    | '/_authenticated/focus'
    | '/_authenticated/tasks'
    | '/_authenticated/rooms'
    | '/_authenticated/sage'
    | '/_authenticated/profile'
    | '/_authenticated/notifications'
    | '/_authenticated/analytics'
    | '/_authenticated/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': { id: '/signup'; path: '/signup'; fullPath: '/signup'; preLoaderRoute: typeof SignupRouteImport; parentRoute: typeof rootRouteImport }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated': { id: '/_authenticated'; path: ''; fullPath: '/'; preLoaderRoute: typeof AuthenticatedRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated/home': { id: '/_authenticated/home'; path: '/home'; fullPath: '/home'; preLoaderRoute: typeof AuthenticatedHomeRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/focus': { id: '/_authenticated/focus'; path: '/focus'; fullPath: '/focus'; preLoaderRoute: typeof AuthenticatedFocusRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/tasks': { id: '/_authenticated/tasks'; path: '/tasks'; fullPath: '/tasks'; preLoaderRoute: typeof AuthenticatedTasksRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/rooms': { id: '/_authenticated/rooms'; path: '/rooms'; fullPath: '/rooms'; preLoaderRoute: typeof AuthenticatedRoomsRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/sage': { id: '/_authenticated/sage'; path: '/sage'; fullPath: '/sage'; preLoaderRoute: typeof AuthenticatedSageRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/profile': { id: '/_authenticated/profile'; path: '/profile'; fullPath: '/profile'; preLoaderRoute: typeof AuthenticatedProfileRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/notifications': { id: '/_authenticated/notifications'; path: '/notifications'; fullPath: '/notifications'; preLoaderRoute: typeof AuthenticatedNotificationsRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/analytics': { id: '/_authenticated/analytics'; path: '/analytics'; fullPath: '/analytics'; preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/settings': { id: '/_authenticated/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof AuthenticatedSettingsRouteImport; parentRoute: typeof AuthenticatedRoute }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedFocusRoute: typeof AuthenticatedFocusRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedSageRoute: typeof AuthenticatedSageRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute,
  AuthenticatedFocusRoute,
  AuthenticatedTasksRoute,
  AuthenticatedRoomsRoute,
  AuthenticatedSageRoute,
  AuthenticatedProfileRoute,
  AuthenticatedNotificationsRoute,
  AuthenticatedAnalyticsRoute,
  AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
